version: "3.11"

services:
  app:
    build: .
    container_name: python-server
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app
